all:
  children:
    Nginx:
    Postgresql:
    Celery:
    Redis:
    Rabbitmq:

Nginx:
  hosts:
    django:
      link_to:
        - sessions
        - database
        - broker

Postgresql:
  hosts:
    database:
      link_to: []

Celery:
  hosts:
    beat:
      link_to:
        - broker
        - database
        - logs
    flower:
      link_to:
        - broker
        - beat
        - logs
        - worker1
        - worker2
    worker1:
      link_to:
        - beat
        - broker
        - logs
    worker2:
      link_to:
        - beat
        - broker
        - logs

Redis:
  hosts:
    logs:
      link_to: []

Rabbitmq:
  hosts:
    broker:
      link_to:
        - logs

Memcached:
  hosts:
    sessions:
      link_to: []
